# Workflow template for testing plugins against PennyLane stable

name: braket-stable-stable
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


env:
  PLUGIN_REPO: aws/amazon-braket-pennylane-plugin-python
  PLUGIN_BRANCH: main
  PLUGIN_PACKAGE: amazon-braket-pennylane-plugin
  PENNYLANE_BRANCH: master
  IBMQX_TOKEN: ${{ secrets.IBMQX_TOKEN }}


jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install pytest pytest-mock pytest-cov flaky
          pip freeze

      - name: Install PennyLane and Plugin
        run: |
          pip install pennylane ${{ env.PLUGIN_PACKAGE }} --upgrade
          pip freeze

      - name: Get plugin version
        id: plugin-version
        run: |
          PLUGIN_VERSION=$(python -c "import pkg_resources as pkg; print(pkg.get_distribution('${{ env.PLUGIN_PACKAGE }}').version)")
          echo ::set-output name=version::$PLUGIN_VERSION

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.PLUGIN_REPO }}
          path: plugin_repo
          ref: v${{ steps.plugin-version.outputs.version }}
      - name: Run PennyLane device integration tests
        run: |
          pl-device-test --device=braket.local.qubit --tb=short --skip-ops --shots=20000
          pl-device-test --device=braket.local.qubit --tb=short --skip-ops

      - name: Run plugin tests
        run: python -m pytest plugin_repo/test/unit_tests/ --tb=short
