# Workflow template for testing plugins against PennyLane latest

name: braket-latest-latest
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


env:
  PLUGIN_REPO: aws/amazon-braket-pennylane-plugin-python
  PLUGIN_BRANCH: main
  PLUGIN_PACKAGE: amazon-braket-pennylane-plugin
  PENNYLANE_BRANCH: master
  TF_VERSION: 2.12.0
  TORCH_VERSION: 2.0.0+cpu


jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install TF
        run: |
          pip install tensorflow~=$TF_VERSION keras~=$TF_VERSION

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install --upgrade pytest-xdist
          pip install pytest pytest-mock pytest-cov flaky pytest-benchmark
          pip freeze

      - name: Install PennyLane and Plugin
        run: |
          pip install git+https://github.com/PennyLaneAI/pennylane.git \
            git+https://github.com/${{ env.PLUGIN_REPO }}.git@${{ env.PLUGIN_BRANCH }}

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.PLUGIN_REPO }}
          path: plugin_repo
          ref: ${{ env.PLUGIN_BRANCH }}

      - name: Run PennyLane device integration tests
        run: |
          pl-device-test --device=braket.local.qubit --tb=short --skip-ops --shots=20000 -k 'not no_0_shots'
          pl-device-test --device=braket.local.qubit --tb=short --skip-ops -k 'not Sample and not no_0_shots'

      - name: Run plugin tests
        run: python -m pytest plugin_repo/test/unit_tests --tb=short
