# Workflow template for testing plugins aginst PennyLane latest

name: lightning-latest-latest
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


env:
  PLUGIN_REPO: PennyLaneAI/pennylane-lightning
  PLUGIN_BRANCH: master
  PLUGIN_PACKAGE: pennylane_lightning
  PENNYLANE_BRANCH: master
  IBMQX_TOKEN: ${{ secrets.IBMQX_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Eigen
        run: |
          # Linux specific build settings
          curl -OsL https://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz
          tar xzf 3.3.7.tar.gz eigen-eigen-323c052e1731/Eigen --strip-components 1
          tar xzf 3.3.7.tar.gz eigen-eigen-323c052e1731/unsupported --strip-components 1
          sudo cp -rf Eigen /usr/local/include
          sudo cp -rf unsupported /usr/local/include

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install --upgrade pybind11
          pip install pytest pytest-mock pytest-cov flaky
          pip freeze

      - name: Install PennyLane and Plugin
        run: |
          pip install git+https://github.com/PennyLaneAI/pennylane.git@${{ env.PENNYLANE_BRANCH }} \
            git+https://github.com/${{ env.PLUGIN_REPO }}.git@${{ env.PLUGIN_BRANCH }}

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.PLUGIN_REPO }}
          path: plugin_repo
          ref: ${{ env.PLUGIN_BRANCH }}

      - name: Run PennyLane device integration tests
        run: |
          pl-device-test --device lightning.qubit --analytic True --skip-ops
          pl-device-test --device lightning.qubit --analytic False --skip-ops --shots=20000

      - name: Run plugin tests
        run: python -m pytest plugin_repo/tests --tb=short
