# Workflow template for testing plugins against PennyLane stable

name: orquestra-latest-stable
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


env:
  PLUGIN_REPO: PennyLaneAI/pennylane-orquestra
  PLUGIN_BRANCH: master
  PLUGIN_PACKAGE: pennylane_orquestra
  PENNYLANE_BRANCH: master
  IBMQX_TOKEN: ${{ secrets.IBMQX_TOKEN }}


jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install pytest pytest-mock pytest-cov flaky
          pip freeze

      - name: Install PennyLane and Plugin
        run: |
          pip install pennylane git+https://github.com/${{ env.PLUGIN_REPO }}.git@${{ env.PLUGIN_BRANCH }}

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.PLUGIN_REPO }}
          path: plugin_repo
          ref: ${{ env.PLUGIN_BRANCH }}
      

      - name: Run plugin tests
        run: python -m pytest plugin_repo/tests --tb=short -k 'not e2e'
