name: Qiskit
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'


jobs:
  core-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - {
              pennylane: 'git+https://github.com/PennyLaneAI/pennylane.git@device-test-cli',
              plugin: 'git+https://github.com/PennyLaneAI/pennylane-qiskit.git'
            }
          # - {pennylane: 'pennylane', plugin: 'pennylane-qiskit'}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install --upgrade qiskit
          pip install pytest pytest-mock pytest-cov flaky
          pip install ${{ matrix.config.pennylane }} ${{ matrix.config.plugin }}

      - uses: actions/checkout@v2
        with:
          repository: PennyLaneAI/pennylane-qiskit
          path: plugin_repo

      - name: Checkout git release
        id: get-version
        if: "!contains(matrix.config.plugin, 'git')"
        run: |
          PLUGIN_VERSION=$(python -c "import pkg_resources as pkg; print(pkg.get_distribution('pennylane_qiskit').version)")
          cd plugin_repo && git checkout v$PLUGIN_VERSION

      - name: Run core plugin tests
        run: |
          pl-device-test --device="qiskit.basicaer" --tb=short
          pl-device-test --device="qiskit.aer" --tb=short

      - name: Run plugin tests
        run: python -m pytest plugin_repo/tests --tb=short
