# Workflow template for testing plugins against PennyLane latest

name: rigetti-stable-latest
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


env:
  PLUGIN_REPO: PennyLaneAI/pennylane-rigetti
  PLUGIN_BRANCH: master
  PLUGIN_PACKAGE: pennylane_rigetti
  PENNYLANE_BRANCH: master
  IBMQX_TOKEN: ${{ secrets.IBMQX_TOKEN }}
  IONQ_API_KEY: ${{ secrets.IONQ_API_KEY }}


jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
            
      - name: Run Rigetti Quilc
        run: docker run --rm -d -p 5555:5555 rigetti/quilc:1.23.0 -R

      - name: Run Rigetti QVM
        run: docker run --rm -d -p 5000:5000 rigetti/qvm -S

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install --upgrade pyquil==2.28.2
          pip install pytest pytest-mock pytest-cov flaky
          pip freeze

      - name: Install PennyLane and Plugin
        run: |
          pip install git+https://github.com/PennyLaneAI/pennylane.git \
          ${{ env.PLUGIN_PACKAGE }} --upgrade

      - name: Get plugin version
        id: plugin-version
        run: |
          PLUGIN_VERSION=$(python -c "import pkg_resources as pkg; print(pkg.get_distribution('${{ env.PLUGIN_PACKAGE }}').version)")
          echo ::set-output name=version::$PLUGIN_VERSION

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.PLUGIN_REPO }}
          path: plugin_repo
          ref: v${{ steps.plugin-version.outputs.version }}

      - name: Run PennyLane device integration tests
        run: |
          pl-device-test --device=rigetti.numpy_wavefunction --tb=short --skip-ops --shots=None
          pl-device-test --device=rigetti.wavefunction --tb=short --skip-ops --shots=20000

      - name: Run plugin tests
        run: python -m pytest plugin_repo/tests --tb=short
